# Autogenerated assembly for expression: 1 + 3 + 4

.class Sample:Obj

.method $constructor
    const 1
    const 3
    call Int:plus
    const 4
    call Int:plus

    const 8  # expected result
    call Int:equals
    call Bool:print
    halt
